# Generated by Django 4.2.7 on 2026-08-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('model_name', models.CharField(choices=[('resnet50', 'ResNet50'), ('mobilenetv2', 'MobileNetV2'), ('baseline_cnn', 'Baseline CNN')], max_length=50)),
                ('prediction', models.CharField(choices=[('real', 'Real'), ('ai_generated', 'AI-Generated')], max_length=30)),
                ('confidence', models.FloatField()),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
